# 服务器环境配置
server:
  port: 8100

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smilcool?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  #  servlet:
  #    # 文件上传下载配置
  #    multipart:
  #      max-file-size: 500MB
  #      max-request-size: 500MB

  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
  # Cache 配置
  cache:
    cache-names: test
    type: redis

  # Swagger 配置
  swagger:
    enabled: true # 生产环境应关闭
    title: Smilcool API DOCS
    description: Smilcool API DOCS - Smilcool 接口文档
    version: 1.0
    contact:
      name: Angus Liu
    base-package: com.smilcool.server.core.controller


# MyBatis-Plus 配置（替代原 MyBatis 配置）
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 下划线风格映射到驼峰命名（便于数据库字段映射到 java 对象属性）
    map-underscore-to-camel-case: true

# Log 配置
logging:
  level:
    # MyBatis 日志级别为 debug
    com.smilcool.server.core.dao: debug
    com.smilcool.server.core.controller: debug

