# 服务器环境配置
server:
  port: 8100

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smilcool?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
#  servlet:
#    # 文件上传下载配置
#    multipart:
#      max-file-size: 500MB
#      max-request-size: 500MB

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.smilcool.server.core.model
  configuration:
    # 下划线风格映射到驼峰命名（便于数据库字段映射到 java 对象属性）
    map-underscore-to-camel-case: true

## log 配置
#logging:
#  level:
#    # mybatis 日志级别为 debug
#    com.candle.core.dao: debug
#    com.candle.common.util: debug
#
## 文件存储配置
#storage:
#  path: D:/Temp/candle/
